@startuml
skinparam style strictuml
skinparam sequenceMessageAlign center
autonumber 1

participant "Server" as S
participant "Current Player" as CP
participant "Other Players" as OP
participant "Broadcast (all Players)" as AP

note over S: Server notifies PhaseObservers\nBuildingEffects with SETUP effects activate

loop for each active BuildingEffect (PhaseObserver)
    S ->> AP: onPlayerResourceChanged(nickname: String, resource: String, newValue: int, delta: int)
end

note over S: SetUpState.onEntryActions() triggered

group #Azure Automatic Setup Sequence
    S -> S: initializeBoard()
    S -> S: randomizeInitialTurnOrder()
end

== Game Setup Notification ==

note over S: Preparing BoardSnapshot (Rows, Tiles, Positions)

S ->> AP: onGameSetupCompleted(turnOrder: List<String>, initialFood: Map<String, Integer>, boardSnapshot: BoardSnapshot)

== Transition to TotemPlacementState ==

S -> S: transitionTo(new TotemPlacementState())

S ->> AP: onPhaseChanged(phase: PhaseType.TOTEM_PLACEMENT, currentPlayer: String)


note over S: Server notifies PhaseObservers\nBuildingEffects with TOTEM_PLACEMENT effects activate

loop for each active BuildingEffect (PhaseObserver)
    S ->> AP: onPlayerResourceChanged(nickname: String, resource: String, newValue: int, delta: int)
end

note over CP #LightGreen: UI Enabled:\nSelect Offer Tile
note over OP #LightPink: UI Disabled:\nWaiting for current player...

@enduml